exchange:
    central: central
management:
    endpoints:
        web:
            exposure:
                include: '*'
queue:
    product:
        delete: product-for-delete
        origin:
            brachs: product-for-central
server:
    port: 8088
    tomcat:
        connection-timeout: 3000
spring:
    application:
        name: product-central
    cache:
        redis:
            time-to-live: 20000
        type: redis
    datasource:
        driverClassName: org.h2.Driver
        hikari:
            maximum-pool-size: 25
        password: S3nh4@#
        platform: h2
        url: jdbc:h2:file:./db_dev/dev;DB_CLOSE_ON_EXIT=TRUE
        username: dev
    h2:
        console:
            enabled: true
            path: /console
            settings:
                trace: false
                web-allow-others: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        properties:
            hibernate:
                format_sql: false
                jdbc:
                    time_zone: UTC-3
                show_sql: true 
                type: trace
                use_sql_comments: false
    rabbitmq:
        host: localhost
        password: password
        port: 5672
        username: user
    redis:
        host: localhost
        port: 6379

